on: [pull_request, push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repository 
        uses: actions/checkout@v3
      
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Install dependencies
        run: npm i
      
      - name: Run ESlint
        run: npm run lint