on: [pull_request, push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repository 
        uses: actions/checkout@v3
      
      - name: Install dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      
      - name: Run ESlint
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: lint